# Site settings
title: Alex Konrad
email: alexkonrad08@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Developer in Brooklyn, NY
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://amkonrad.com" # the base hostname & protocol for your site
twitter_username: alexkonrad
github_username:  alexkonrad

# Build settings
markdown: kramdown
